add food security discovery
NASA-IMPACT/delta-config pull request #123
Opened 2022-10-20 22:35 UTC by aboydnw

for the agriculture thematic area

2022-10-27 13:52 UTC, danielfdsilva requested changes
Nice to see another story!

Couple of things:
- The cover image is very heavy. Try to run it through http://compressor.io/ to see if it helps. You can also probably reduce the size, but never below 1920.
- The gif is also pretty big. Compressor may help, but with the animation there may not be a lot to do.
- If it makes sense, consider using the image blocks with images on the sides, as it gives a more interesting flow to the story.

Let me know if you need help

2022-10-27 13:52 UTC, danielfdsilva commented on discoveries/agriculture-food-security-east-africa.discoveries.mdx
> +   Story by [Michael Carlowicz](https://earthobservatory.nasa.gov/about/michael-carlowicz).*
What is the purpose with the `*`?

2022-10-28 23:53 UTC, aboydnw commented
Alright I think I am lost haha. I pushed a couple changes based on your comments @danielfdsilva but I don't see them reflected here. When I view the git log this is what I see:
![image](https://user-images.githubusercontent.com/92742765/198751598-9962705b-8cef-4de5-8826-691806f782dd.png)
I'm not sure if that's correct, but the origin is a few behind my recent changes. Any ideas what I am doing wrong?

2022-11-02 15:30 UTC, aboydnw commented
okay @danielfdsilva now it is up to date! :) ready for second review

2022-11-02 17:45 UTC, danielfdsilva approved these changes
@aboydnw Decreased the cover image to 2500px wide and added a content fix. Have a look at the last commit.

Otherwise all good.

2022-11-02 18:00 UTC, merged