Add ECCO dataset
NASA-IMPACT/delta-config pull request #131
Opened 2022-11-04 20:16 UTC by ividito

Related: https://github.com/NASA-IMPACT/veda-data-pipelines/pull/219 and https://github.com/NASA-IMPACT/veda-data-pipelines/issues/217

Add configuration for ECCO ocean state estimate dataset.

2022-11-14 09:55 UTC, danielfdsilva commented
@ividito Is this ready for review?

2022-11-14 14:41 UTC, ividito commented
> @ividito Is this ready for review?

Yes, this should be ready to go.

2022-11-14 15:41 UTC, danielfdsilva requested changes

2022-11-14 15:41 UTC, danielfdsilva commented on datasets/ecco-surface-height-change.data.mdx
> +  src: ::file ./ecco-surface-height-change--dataset-cover.jpg
With 1.8MB this image is pretty big. Consider cutting it down to 1920 on the wide side and running it through http://compressor.io/

2022-11-14 15:41 UTC, danielfdsilva commented on datasets/ecco-surface-height-change.data.mdx
> +    Gridded global sea-surface height change from 1992 to 2017 from the Estimating the Circulation and Climate of the Ocean (ECCO) ocean state estimate. The dataset was calculated as the difference b
Use `PO.DAAC` for the link, instead of showing the actual url

2022-11-15 10:55 UTC, danielfdsilva approved these changes
Fantastic! :D

2022-11-18 13:43 UTC, j08lue commented
Can we merge this, @ividito?

2022-11-18 13:50 UTC, merged