Ocean thematic area and Phytoplankton story
NASA-IMPACT/delta-config pull request #98
Opened 2022-08-08 15:57 UTC by danielfdsilva

First pass at the Ocean thematic area and Phytoplankton story.

Story content from: https://docs.google.com/document/d/1BaxmvzpqS29VP8mg3bPvslz_4v2OCRbt/edit

Missing some descriptions. Marked with a `<TODO: ...>`

2022-08-11 22:57 UTC, aboydnw commented
@danielfdsilva for some reason the netlify preview doesn't work for me. Does it work on your end?

I received an email from Dee-Dee re: the map for this story. From reading it below, it sounds like maybe this will be dependent on https://github.com/NASA-IMPACT/delta-config/issues/85 ? If so, maybe we can use an image for now and change it once the dataset is configured. What do you think?

A few details about the graphics for the second set of images, they are from the Cyanobacteria Assessment Network (CyAN) data set.  https://oceancolor.gsfc.nasa.gov/projects/cyan/

The imagery is from a combination of data from OLCIs on Sentinel-3A and 3B. Combined the sensors have near daily temporal coverage with 300m spatial resolution.  The website has links to GEOTIFF imagery and to the data in a spreadsheet format.  The Data Access links are on the right side of the webpage. The File Search Tool is easy to use and gives the imagery. You can pick the dates and if you prefer a daily or 7-day composite and then click on the tile that is of interest or click to have the full US image. Once you submit you will see a list of files. To download the files, you will need to create a user account. In the imagery the rainbow colors indicate the presence of cyanobacteria,  the light grey color means there was data, but the cyanobacteria are below the detection level and black means there was no data, because of clouds or another quality control flag.  

Beyond the CyAN satellite product, which estimates cyanobacteria concentration I the water the website also has daily true color imagery which could perhaps add to the story. There is an example below.

I made a few comments on the text and attached the document. Let me know if you have questions. Thank you for sharing the HABs story and creating awareness of our data.

Best,

Bridget


Below images are the true color (top) and CyAN satellite product (bottom) estimating cyanobacteria in the water from September 2, 2021. Images are produced by the Cyanobacteria Assessment Network (CyAN) using data from OLCI on Sentinel-3A and 3B.

![image](https://user-images.githubusercontent.com/92742765/184256062-8258252b-aad6-4461-9668-3ba9995e8d7b.png)

2022-08-12 10:32 UTC, danielfdsilva commented
@aboydnw This thematic area still needs its own datasets. Once we have them we can add interactive maps, like you said. I don't know if they were ingested already or its details.

I included the images as a compare option. I think it looks cool.
<img width="927" alt="image" src="https://user-images.githubusercontent.com/1090606/184337078-0a1efa0a-c492-4042-8f7d-27c4c03fee61.png">

The netlify preview should be working now

2022-08-12 17:16 UTC, aboydnw requested changes
This looks great! Just a couple small text changes

1. Text for the description:  "A combination of ground- and satellite-based tools provides a regional to global understanding of the impacts of water quality"
2. Text for the ocean story description: "Satellites track phytoplankton's algal blooms and its impact on tourism and fisheries"
3. Initial header for ocean story (to replace the header moving to the description): "Phytoplankton: Beneficial or Harmful?"

2022-08-16 14:58 UTC, aboydnw approved these changes

2022-08-16 15:10 UTC, merged